# netlify.toml
[build]
  base = "project" # Your project folder
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://survey-pro-api.runasp.net/api/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/files/*"
  to = "http://survey-pro-api.runasp.net/api/files/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200