# netlify.toml

[build]
  base = "project" 
  publish = "dist" 
  command = "npm run build"

# Handle Mixed Content (CORS Error)
[[redirects]]
  from = "/api/*"
  to = "https://survey-pro-api.runasp.net/api/:splat"
  status = 200
  force = true

# Redirect all routes to index.html (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment settings for production
[context.production.environment]
  NODE_ENV = "production"
